2024-09-10 00:48:23 - __main__        - INFO     - Bot is starting up... (shame_script.py:16)
2024-09-10 00:48:23 - discord.client  - WARNING  - PyNaCl is not installed, voice will NOT be supported (client.py:300)
2024-09-10 00:48:23 - discord.client  - INFO     - logging in using static token (client.py:611)
2024-09-10 00:48:23 - discord.gateway - INFO     - Shard ID None has connected to Gateway (Session ID: 163ae1c8800466016bbf1a8b990777d6). (gateway.py:563)
2024-09-10 00:48:25 - __main__        - INFO     - Bot is ready. Logged in as test_bot#6431 (shame_script.py:148)
2024-09-10 00:48:26 - __main__        - INFO     - Command synced: signup (shame_script.py:153)
2024-09-10 00:48:26 - __main__        - INFO     - {
  "userId": 1,
  "id": 1,
  "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
  "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
} (shame_script.py:159)
2024-09-10 00:55:52 - __main__        - INFO     - Bot is starting up... (shame_script.py:16)
2024-09-10 00:55:52 - discord.client  - WARNING  - PyNaCl is not installed, voice will NOT be supported (client.py:300)
2024-09-10 00:55:52 - discord.client  - INFO     - logging in using static token (client.py:611)
2024-09-10 00:55:53 - discord.gateway - INFO     - Shard ID None has connected to Gateway (Session ID: f8795ba5cc24847862ed64529069da95). (gateway.py:563)
2024-09-10 00:55:55 - __main__        - INFO     - Bot is ready. Logged in as test_bot#6431 (shame_script.py:148)
2024-09-10 00:55:55 - __main__        - INFO     - Command synced: signup (shame_script.py:153)
2024-09-10 00:55:56 - discord.client  - ERROR    - Ignoring exception in on_ready (client.py:523)
Traceback (most recent call last):
  File "/home/rocket3989/github/shame-bot/.venv/lib/python3.12/site-packages/aiohttp/connector.py", line 1301, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rocket3989/github/shame-bot/.venv/lib/python3.12/site-packages/aiohttp/connector.py", line 911, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rocket3989/github/shame-bot/.venv/lib/python3.12/site-packages/aiohttp/connector.py", line 948, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rocket3989/github/shame-bot/.venv/lib/python3.12/site-packages/aiohttp/resolver.py", line 37, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 901, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 976, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rocket3989/github/shame-bot/.venv/lib/python3.12/site-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/home/rocket3989/github/shame-bot/shame_script.py", line 158, in on_ready
    response = await session.get("https://jsonplaceholder.typicoddsae.com/posts/1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rocket3989/github/shame-bot/.venv/lib/python3.12/site-packages/aiohttp/client.py", line 657, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rocket3989/github/shame-bot/.venv/lib/python3.12/site-packages/aiohttp/connector.py", line 564, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rocket3989/github/shame-bot/.venv/lib/python3.12/site-packages/aiohttp/connector.py", line 975, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rocket3989/github/shame-bot/.venv/lib/python3.12/site-packages/aiohttp/connector.py", line 1307, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host jsonplaceholder.typicoddsae.com:443 ssl:default [Name or service not known]
2024-09-10 00:57:48 - __main__        - INFO     - Bot is starting up... (shame_script.py:16)
2024-09-10 00:57:48 - discord.client  - WARNING  - PyNaCl is not installed, voice will NOT be supported (client.py:300)
2024-09-10 00:57:48 - discord.client  - INFO     - logging in using static token (client.py:611)
2024-09-10 00:57:49 - discord.gateway - INFO     - Shard ID None has connected to Gateway (Session ID: dfb6897d25e532fc2e2303b3e657d0b5). (gateway.py:563)
2024-09-10 00:57:51 - __main__        - INFO     - Bot is ready. Logged in as test_bot#6431 (shame_script.py:148)
2024-09-10 00:57:51 - __main__        - INFO     - Command synced: signup (shame_script.py:153)
2024-09-10 00:57:51 - discord.client  - ERROR    - Ignoring exception in on_ready (client.py:523)
Traceback (most recent call last):
  File "/home/rocket3989/github/shame-bot/.venv/lib/python3.12/site-packages/aiohttp/connector.py", line 1301, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rocket3989/github/shame-bot/.venv/lib/python3.12/site-packages/aiohttp/connector.py", line 911, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rocket3989/github/shame-bot/.venv/lib/python3.12/site-packages/aiohttp/connector.py", line 948, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rocket3989/github/shame-bot/.venv/lib/python3.12/site-packages/aiohttp/resolver.py", line 37, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 901, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 976, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rocket3989/github/shame-bot/.venv/lib/python3.12/site-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/home/rocket3989/github/shame-bot/shame_script.py", line 158, in on_ready
    response = await session.get("https://jsonplaceholder.xxx")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rocket3989/github/shame-bot/.venv/lib/python3.12/site-packages/aiohttp/client.py", line 657, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rocket3989/github/shame-bot/.venv/lib/python3.12/site-packages/aiohttp/connector.py", line 564, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rocket3989/github/shame-bot/.venv/lib/python3.12/site-packages/aiohttp/connector.py", line 975, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rocket3989/github/shame-bot/.venv/lib/python3.12/site-packages/aiohttp/connector.py", line 1307, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host jsonplaceholder.xxx:443 ssl:default [Name or service not known]
2024-09-10 00:58:59 - __main__        - INFO     - Bot is starting up... (shame_script.py:16)
2024-09-10 00:58:59 - discord.client  - WARNING  - PyNaCl is not installed, voice will NOT be supported (client.py:300)
2024-09-10 00:58:59 - discord.client  - INFO     - logging in using static token (client.py:611)
2024-09-10 00:59:00 - discord.gateway - INFO     - Shard ID None has connected to Gateway (Session ID: e35a736335fae5af5f885bd652a817fc). (gateway.py:563)
2024-09-10 00:59:02 - __main__        - INFO     - Bot is ready. Logged in as test_bot#6431 (shame_script.py:148)
2024-09-10 00:59:02 - __main__        - INFO     - Command synced: signup (shame_script.py:153)
2024-09-10 00:59:02 - discord.client  - ERROR    - Ignoring exception in on_ready (client.py:523)
Traceback (most recent call last):
  File "/home/rocket3989/github/shame-bot/.venv/lib/python3.12/site-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/home/rocket3989/github/shame-bot/shame_script.py", line 158, in on_ready
    response = await session.get("jsonplaceholder.xxx")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rocket3989/github/shame-bot/.venv/lib/python3.12/site-packages/aiohttp/client.py", line 586, in _request
    raise err_exc_cls(url)
aiohttp.client_exceptions.InvalidUrlClientError: jsonplaceholder.xxx
2024-09-10 01:00:42 - __main__        - INFO     - Bot is starting up... (shame_script.py:16)
2024-09-10 01:00:42 - discord.client  - WARNING  - PyNaCl is not installed, voice will NOT be supported (client.py:300)
2024-09-10 01:00:42 - discord.client  - INFO     - logging in using static token (client.py:611)
2024-09-10 01:00:43 - discord.gateway - INFO     - Shard ID None has connected to Gateway (Session ID: 044ca37418a2a9e29744eddff2d98dbb). (gateway.py:563)
2024-09-10 01:00:45 - __main__        - INFO     - Bot is ready. Logged in as test_bot#6431 (shame_script.py:148)
2024-09-10 01:00:45 - __main__        - INFO     - Command synced: signup (shame_script.py:153)
2024-09-10 01:00:45 - __main__        - INFO     - <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/dsagfdsag</code> was not found on this server.  <ins>That’s all we know.</ins>
 (shame_script.py:159)
2024-09-10 01:17:00 - __main__        - INFO     - Bot is starting up... (shame_script.py:16)
2024-09-10 01:17:00 - discord.client  - WARNING  - PyNaCl is not installed, voice will NOT be supported (client.py:300)
2024-09-10 01:17:00 - discord.client  - INFO     - logging in using static token (client.py:611)
2024-09-10 01:17:01 - discord.gateway - INFO     - Shard ID None has connected to Gateway (Session ID: fd7b52d0dffa4c4580b712c670b36bff). (gateway.py:563)
2024-09-10 01:17:03 - __main__        - INFO     - Bot is ready. Logged in as test_bot#6431 (shame_script.py:148)
2024-09-10 01:17:04 - __main__        - INFO     - Command synced: signup (shame_script.py:153)
2024-09-10 01:17:04 - aiohttp         - INFO     - http://google.com/dsagfdsag (log_setup.py:71)
2024-09-10 01:17:04 - aiohttp         - INFO     - Response Status: 404 (log_setup.py:74)
2024-09-10 01:17:04 - discord.client  - ERROR    - Ignoring exception in on_ready (client.py:523)
Traceback (most recent call last):
  File "/home/rocket3989/github/shame-bot/.venv/lib/python3.12/site-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/home/rocket3989/github/shame-bot/shame_script.py", line 159, in on_ready
    logger.info(await response.json())
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rocket3989/github/shame-bot/.venv/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1199, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 404, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url='http://google.com/dsagfdsag'
2024-09-10 01:21:56 - __main__        - INFO     - Bot is starting up... (shame_script.py:16)
2024-09-10 01:21:56 - discord.client  - WARNING  - PyNaCl is not installed, voice will NOT be supported (client.py:300)
2024-09-10 01:21:56 - discord.client  - INFO     - logging in using static token (client.py:611)
2024-09-10 01:21:57 - discord.gateway - INFO     - Shard ID None has connected to Gateway (Session ID: 1de96b3ebf00fe112cfc16ef274da1fb). (gateway.py:563)
2024-09-10 01:21:59 - __main__        - INFO     - Bot is ready. Logged in as test_bot#6431 (shame_script.py:148)
2024-09-10 01:21:59 - __main__        - INFO     - Command synced: signup (shame_script.py:153)
2024-09-10 01:21:59 - aiohttp         - ERROR    - Request Error: http://google.com/dsagfdsag 404 (log_setup.py:75)
2024-09-10 01:21:59 - __main__        - INFO     - <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/dsagfdsag</code> was not found on this server.  <ins>That’s all we know.</ins>
 (shame_script.py:159)
2024-09-10 01:25:24 - __main__        - INFO     - Bot is starting up... (shame_script.py:16)
2024-09-10 01:25:25 - discord.client  - WARNING  - PyNaCl is not installed, voice will NOT be supported (client.py:300)
2024-09-10 01:25:25 - discord.client  - INFO     - logging in using static token (client.py:611)
2024-09-10 01:25:25 - discord.gateway - INFO     - Shard ID None has connected to Gateway (Session ID: 61b77ab31d0124ac702a2efee14fd71e). (gateway.py:563)
2024-09-10 01:25:27 - __main__        - INFO     - Bot is ready. Logged in as test_bot#6431 (shame_script.py:148)
2024-09-10 01:25:28 - __main__        - INFO     - Command synced: signup (shame_script.py:153)
2024-09-10 01:25:28 - aiohttp         - ERROR    - Request Error: http://google.com/dsagfdsag 404 (log_setup.py:71)
2024-09-10 01:25:28 - __main__        - INFO     - <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/dsagfdsag</code> was not found on this server.  <ins>That’s all we know.</ins>
 (shame_script.py:159)
2024-09-10 01:25:38 - __main__        - INFO     - Bot is starting up... (shame_script.py:16)
2024-09-10 01:25:38 - discord.client  - WARNING  - PyNaCl is not installed, voice will NOT be supported (client.py:300)
2024-09-10 01:25:38 - discord.client  - INFO     - logging in using static token (client.py:611)
2024-09-10 01:25:39 - discord.gateway - INFO     - Shard ID None has connected to Gateway (Session ID: 91691e5bbe01f6194b0f6c5fe6832200). (gateway.py:563)
2024-09-10 01:25:41 - __main__        - INFO     - Bot is ready. Logged in as test_bot#6431 (shame_script.py:148)
2024-09-10 01:26:28 - __main__        - INFO     - Command synced: signup (shame_script.py:153)
2024-09-10 01:26:28 - aiohttp         - ERROR    - Request Error: http://google.com/dsagfdsag 404 (log_setup.py:71)
2024-09-10 01:26:28 - __main__        - INFO     - <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/dsagfdsag</code> was not found on this server.  <ins>That’s all we know.</ins>
 (shame_script.py:159)
2024-09-10 01:28:07 - aiohttp         - ERROR    - Request Error: http://google.com/dsagfdsag 404 (log_setup.py:71)
2024-09-10 01:28:07 - __main__        - INFO     - <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/dsagfdsag</code> was not found on this server.  <ins>That’s all we know.</ins>
 (test.py:13)
2024-09-10 01:28:25 - aiohttp         - ERROR    - Request Error: http://google.com/dsagfdsag 404 (log_setup.py:71)
2024-09-10 01:28:25 - __main__        - INFO     - <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/dsagfdsag</code> was not found on this server.  <ins>That’s all we know.</ins>
 (test.py:13)
2024-09-10 01:28:34 - aiohttp         - ERROR    - Request Error: http://google.com/dsagfdsag 404 (log_setup.py:71)
2024-09-10 01:28:34 - __main__        - INFO     - <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/dsagfdsag</code> was not found on this server.  <ins>That’s all we know.</ins>
 (test.py:13)
2024-09-10 01:28:40 - aiohttp         - ERROR    - Request Error: http://google.com/dsagfdsag 404 (log_setup.py:71)
2024-09-10 01:28:40 - __main__        - INFO     - <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/dsagfdsag</code> was not found on this server.  <ins>That’s all we know.</ins>
 (test.py:13)
2024-09-10 01:29:30 - aiohttp         - ERROR    - Request Error: http://google.com/dsagfdsag 404 (log_setup.py:71)
2024-09-10 01:29:30 - __main__        - INFO     - <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/dsagfdsag</code> was not found on this server.  <ins>That’s all we know.</ins>
 (test.py:13)
2024-09-10 01:30:50 - aiohttp         - ERROR    - Request Error: http://google.com/dsagfdsag 404 (log_setup.py:71)
2024-09-10 01:30:50 - __main__        - INFO     - <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/dsagfdsag</code> was not found on this server.  <ins>That’s all we know.</ins>
 (test.py:13)
2024-09-10 01:31:15 - aiohttp         - ERROR    - Request Error: http://google.com/dsagfdsag 404 (log_setup.py:71)
2024-09-10 01:31:15 - __main__        - INFO     - <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/dsagfdsag</code> was not found on this server.  <ins>That’s all we know.</ins>
 (test.py:13)
2024-09-10 01:31:17 - aiohttp         - ERROR    - Request Error: http://google.com/dsagfdsag 404 (log_setup.py:71)
2024-09-10 01:31:17 - __main__        - INFO     - <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/dsagfdsag</code> was not found on this server.  <ins>That’s all we know.</ins>
 (test.py:13)
2024-09-10 01:31:26 - aiohttp         - ERROR    - Request Error: http://google.com/dsagfdsag 404 (log_setup.py:71)
2024-09-10 01:34:00 - aiohttp         - ERROR    - Request Error: http://google.com/dsagfdsag 404 (log_setup.py:72)
2024-09-10 01:34:14 - aiohttp         - ERROR    - Request Error: http://google.com/dsagfdsag 404 (log_setup.py:72)
2024-09-10 01:34:49 - aiohttp         - ERROR    - Request Error: http://google.com/dsagfdsag 404 (log_setup.py:72)
2024-09-10 01:35:34 - aiohttp         - ERROR    - Request Error: http://google.com/dsagfdsag 404 (log_setup.py:71)
2024-09-10 01:35:58 - aiohttp         - ERROR    - Request Error: http://google.com/dsagfdsag 404 (test.py:12)
2024-09-10 01:36:05 - aiohttp         - ERROR    - Request Error: http://google.com/dsagfdsag 404 (events.py:88)
2024-09-10 01:36:16 - aiohttp         - ERROR    - Request Error: http://google.com/dsagfdsag 404 (test.py:12)
2024-09-10 01:36:56 - __main__        - INFO     - Bot is starting up... (shame_script.py:16)
2024-09-10 01:36:56 - discord.client  - WARNING  - PyNaCl is not installed, voice will NOT be supported (client.py:300)
2024-09-10 01:36:56 - discord.client  - INFO     - logging in using static token (client.py:611)
2024-09-10 01:36:57 - discord.gateway - INFO     - Shard ID None has connected to Gateway (Session ID: 9d28365fe06cb02996b44b27cb1a7923). (gateway.py:563)
2024-09-10 01:36:59 - __main__        - INFO     - Bot is ready. Logged in as test_bot#6431 (shame_script.py:148)
2024-09-10 01:36:59 - __main__        - INFO     - Command synced: signup (shame_script.py:153)
2024-09-10 01:36:59 - aiohttp         - ERROR    - Request Error: http://google.com/dsagfdsag 404 (shame_script.py:158)
2024-09-10 01:36:59 - __main__        - INFO     - <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/dsagfdsag</code> was not found on this server.  <ins>That’s all we know.</ins>
 (shame_script.py:159)
2024-09-10 03:05:22 - __main__        - INFO     - Bot is starting up... (shame_script.py:16)
2024-09-10 03:05:22 - discord.client  - WARNING  - PyNaCl is not installed, voice will NOT be supported (client.py:300)
2024-09-10 03:05:22 - discord.client  - INFO     - logging in using static token (client.py:611)
2024-09-10 03:05:23 - discord.gateway - INFO     - Shard ID None has connected to Gateway (Session ID: 0b4f2ee662458a9978290e9cc05bc903). (gateway.py:563)
2024-09-10 03:05:25 - __main__        - INFO     - Bot is ready. Logged in as test_bot#6431 (shame_script.py:151)
2024-09-10 03:05:25 - __main__        - INFO     - Command synced: signup (shame_script.py:156)
2024-09-10 03:22:12 - __main__        - INFO     - Bot is starting up... (shame_script.py:16)
2024-09-10 03:22:12 - discord.client  - WARNING  - PyNaCl is not installed, voice will NOT be supported (client.py:300)
2024-09-10 03:22:12 - discord.client  - INFO     - logging in using static token (client.py:611)
2024-09-10 03:22:12 - discord.gateway - INFO     - Shard ID None has connected to Gateway (Session ID: 3139e561278e793e25dd48f5d7760835). (gateway.py:563)
2024-09-10 03:22:14 - __main__        - INFO     - Bot is ready. Logged in as test_bot#6431 (shame_script.py:159)
2024-09-10 03:22:15 - __main__        - INFO     - Command synced: signup (shame_script.py:164)
2024-09-10 03:23:00 - __main__        - INFO     - Fetching and sending tasks for channel: 1282849216430866432 (shame_script.py:196)
2024-09-10 03:23:00 - __main__        - INFO     - Processing tasks for user: kevinzefu@gmail.com (shame_script.py:206)
2024-09-10 03:23:02 - __main__        - INFO     - Task 5674963926 updated successfully. (shame_script.py:131)
2024-09-10 03:23:03 - __main__        - INFO     - Task 6118837989 updated successfully. (shame_script.py:131)
2024-09-10 03:23:04 - __main__        - INFO     - Task 6785170169 updated successfully. (shame_script.py:131)
2024-09-10 03:23:04 - __main__        - INFO     - Task 6785573045 updated successfully. (shame_script.py:131)
2024-09-10 03:23:05 - __main__        - INFO     - Task 7896057704 updated successfully. (shame_script.py:131)
2024-09-10 03:23:05 - __main__        - INFO     - Task 7896060059 updated successfully. (shame_script.py:131)
2024-09-10 03:23:06 - __main__        - INFO     - Task 7896060245 updated successfully. (shame_script.py:131)
2024-09-10 03:23:06 - __main__        - INFO     - Processing tasks for user: jathanas1998@gmail.com (shame_script.py:206)
2024-09-10 03:23:08 - __main__        - INFO     - Task 8276506127 updated successfully. (shame_script.py:131)
2024-09-10 03:23:08 - __main__        - INFO     - Task 8371195133 updated successfully. (shame_script.py:131)
2024-09-10 03:23:08 - __main__        - INFO     - Processing tasks for user: rocket3989@gmail.com (shame_script.py:206)
2024-09-10 03:23:10 - __main__        - INFO     - Task 8272558658 updated successfully. (shame_script.py:131)
2024-09-10 03:27:24 - __main__        - INFO     - Bot is starting up... (shame_script.py:16)
2024-09-10 03:27:24 - discord.client  - WARNING  - PyNaCl is not installed, voice will NOT be supported (client.py:300)
2024-09-10 03:27:24 - discord.client  - INFO     - logging in using static token (client.py:611)
2024-09-10 03:27:25 - discord.gateway - INFO     - Shard ID None has connected to Gateway (Session ID: bac63ce495db26d27b715a0173f9b559). (gateway.py:563)
2024-09-10 03:27:27 - __main__        - INFO     - Bot is ready. Logged in as test_bot#6431 (shame_script.py:159)
2024-09-10 03:27:27 - __main__        - INFO     - Command synced: signup (shame_script.py:164)
2024-09-10 03:28:00 - __main__        - INFO     - Fetching and sending tasks for channel: 1282849216430866432 (shame_script.py:196)
2024-09-10 03:28:00 - __main__        - INFO     - Processing tasks for user: kevinzefu@gmail.com (shame_script.py:206)
2024-09-10 03:28:01 - __main__        - INFO     - Processing tasks for user: jathanas1998@gmail.com (shame_script.py:206)
2024-09-10 03:28:05 - __main__        - INFO     - Processing tasks for user: rocket3989@gmail.com (shame_script.py:206)
